server.port=8080
spring.application.name=orm-backend

gemini.api.key= AIzaSyAYB2Bs1qYef3JqzlPr12tOWP9IjgNz7GU
gemini.model= gemini-3.5-flash
gemini.url= https://generativelanguage.googleapis.com/v1beta/openai/

google.places.api.key=DISABLED
